OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "proj_xxxxxxxxxxxxxxxxxx"


