OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "proj_xxxxxxxxxxxxxxxxxx"


